### ISSUE TITLE
Invalid Authentication

### ISSUE THREAD

**Issue by LiamKarlMitchell** [jansmolders86/mediacenterjs#116]
I keep getting this over and over when I goto loop up data for movies.

```
E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\lib\moviedb.js:41
    else throw new Error('Invalid authentication');
               ^
Error: Invalid authentication
    at E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\lib\moviedb.js:41:16
    at Request.callback (E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\node_modules\superag
ent\lib\node\index.js:730:3)
    at Request.<anonymous> (E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\node_modules\supe
ragent\lib\node\index.js:135:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\node_modu
les\superagent\lib\node\index.js:886:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

Metadata fetching for movie complete...
Loading movie data... true
Child process exited for:  movie
Metadata fetcher error:  { [Error: Command failed:
E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\lib\moviedb.js:41
    else throw new Error('Invalid authentication');
               ^
Error: Invalid authentication
    at E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\lib\moviedb.js:41:16
    at Request.callback (E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\node_modules\superag
ent\lib\node\index.js:730:3)
    at Request.<anonymous> (E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\node_modules\supe
ragent\lib\node\index.js:135:10)
    at Request.EventEmitter.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (E:\Documents\GitHub\mediacenterjs\node_modules\moviedb\node_modu
les\superagent\lib\node\index.js:886:12)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)
] killed: false, code: 8, signal: null }
Getting data...
Fetching movie data...
Meta gathering started: Movies
```

**Comment by soyuka** [comment]
Hi,

Is this related ? 

```

/home/soyuka/mediacenterjs/node_modules/moviedb/lib/moviedb.js:41
    else throw res.error;
                  ^
Error: cannot GET /3/authentication/token/new?api_key=7983694ec277523c31ff1212e35e5fa3 (429)
    at Response.toError (/home/soyuka/mediacenterjs/node_modules/moviedb/node_modules/superagent/lib/node/response.js:106:13)
    at Response.setStatusProperties (/home/soyuka/mediacenterjs/node_modules/moviedb/node_modules/superagent/lib/node/response.js:193:12)
    at new Response (/home/soyuka/mediacenterjs/node_modules/moviedb/node_modules/superagent/lib/node/response.js:42:8)
    at IncomingMessage.<anonymous> (/home/soyuka/mediacenterjs/node_modules/moviedb/node_modules/superagent/lib/node/index.js:935:22)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:486:13)
```
