### ISSUE TITLE
Crash when viewing Movies

### ISSUE THREAD

**Issue by haarts** [jansmolders86/mediacenterjs#209]
I've just done a fresh clone from the repo and ran it. After pointing MCJS to my Movies directory and going to the `/movies` url I only see "Loading, please wait". On the command line I see: 

```
/home/harm/mediacenterjs/lib/utils/moviedb-wrapper.js:37
        var promise = new Promise(function(res, rej) {
                          ^
ReferenceError: Promise is not defined
    at search (/home/harm/mediacenterjs/lib/utils/moviedb-wrapper.js:37:27)
    at Object.searchMovie (/home/harm/mediacenterjs/lib/utils/moviedb-wrapper.js:73:20)
    at Object.exports.processFile (/home/harm/mediacenterjs/apps/movies/metadata-processor.js:32:13)
    at /home/harm/mediacenterjs/lib/media-handler.js:51:30
    at Function._.each._.forEach (/home/harm/mediacenterjs/node_modules/underscore/underscore.js:153:9)
    at /home/harm/mediacenterjs/lib/media-handler.js:50:7
    at Walker.<anonymous> (/home/harm/mediacenterjs/lib/utils/file-utils.js:51:9)
    at Walker.emit (events.js:92:17)
<snip>
```

I'm runninig on Ubuntu 14.04, NodeJS 0.10.37, sha 7acb4d3.
I tried tag v0.1.0 without any luck as well as the 0.1.2 auto update variant. 

The TV series don't work either but I'm suspecting I'm doing it wrong; my directory layout is `./series/Serie Name/Season number/s01e01 - episode name.mp4`. In other words the top level dir contains only other directories.

**Comment by jansmolders86** [comment]
Please update your Nodejs. the Promise isn't a know function in the older nodeJs
Read more here:
https://github.com/jansmolders86/mediacenterjs/wiki/User-manual:---installing-MediacenterJS#build-nodejs-for-arm-devices-running-ubuntu--debian-

**Comment by haarts** [comment]
That did it! Thanks.
