### ISSUE TITLE
Plugin list crashes

### ISSUE THREAD

**Issue by haarts** [jansmolders86/mediacenterjs#210]
When clicking on 'Plugins' the app crashes with:

```
info: Looking for available plugins...
NAME                  DESCRIPTION                                                   AUTHOR          DATE              VERSION KEYWORDS
mediacenterjs-googlemusic WIP: A Google Music app for mediacenterjs                 =jansmolders86  2014-12-18 10:51  0.0.13  mediacenterjs Google Music
mediacenterjs-javascript-jabber MediacenterJS plugin for the Javascript Jabber podcast =terrymooreii   2013-10-12 01:03  0.1.0   mediacenterjs music javascript jabber podcast
mediacenterjs-maps    A Google Maps app for mediacenterjs                           =jansmolders86  2014-11-28 13:33  1.0.1   mediacenterjs Google Maps
mediacenterjs-nerdist A Nerdist app for mediacenterjs                               =jansmolders86  2014-11-27 11:49  1.0.1   mediacenterjs Nerdist podcast
mediacenterjs-plugin-generator MediacenterJS plugin generator                       =terrymooreii   2013-11-16 01:53  0.0.3   mediacenterjs plugin generator
mediacenterjs-soccer  Watch streaming soccer                                        =pocketjake     2014-05-04 13:56  0.0.3   soccer streaming mediacenterjs nodejs
mediacenterjs-spotify WIP (Experimental): A Spotify app for MediacenterJS. Requires Node-Gyp to work. =jansmolders86 2014-11-28 13:57  0.0.5   mediacenterjs spotify

/home/harm/mediacenterjs/apps/plugins/plugins-functions.js:107
                    author: pluginObj.author.replace('=',''),
                                             ^
TypeError: Cannot call method 'replace' of undefined
    at /home/harm/mediacenterjs/apps/plugins/plugins-functions.js:107:46
    at Array.map (native)
    at /home/harm/mediacenterjs/apps/plugins/plugins-functions.js:99:14
    at /home/harm/mediacenterjs/apps/plugins/plugins-functions.js:80:25
    at /home/harm/mediacenterjs/node_modules/npm/lib/search.js:54:5
    at /home/harm/mediacenterjs/node_modules/npm/lib/search.js:62:12
    at /home/harm/mediacenterjs/node_modules/npm/node_modules/npm-registry-client/lib/get.js:93:14
    at /home/harm/mediacenterjs/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:103:5
    at Object.oncomplete (fs.js:108:15)

```

I'm runninig on Ubuntu 14.04, NodeJS 0.10.37, sha 7acb4d3.

**Comment by jansmolders86** [comment]
I pushed a fix for this issue, would you mind trying again?

**Comment by haarts** [comment]
It no longer crashes. But now none of the plugins has an author. Which seems odd. Also I would, in the case of an absent author, use 'unknown' in stead of an empty string. Just my 2cnts.

**Comment by jansmolders86** [comment]
Good call :) Will change. Bedankt voor je hulp!
