### ISSUE TITLE
Can't start mediacenterjs 0.1.2 on windows 10.

### ISSUE THREAD

**Issue by mgara** [jansmolders86/mediacenterjs#211]
`
TypeError: Object [object Promise] has no method 'tap'
   at ConnectionManager.getConnection (C:\MediacenterJS\node_modules\sequelize\lib\dialects\sqlite\connection-manager.js:52:6)
   at Transaction.prepareEnvironment (C:\MediacenterJS\node_modules\sequelize\lib\transaction.js:179:103)
   at Sequelize.transaction (C:\MediacenterJS\node_modules\sequelize\lib\sequelize.js:1229:24)
   at Model.findOrCreate (C:\MediacenterJS\node_modules\sequelize\lib\model.js:1892:25)
   at Object.exports.storeDeviceInfo (C:\MediacenterJS\lib\utils\device-utils.js:30:12)
   at app.post.incommingDevice (C:\MediacenterJS\index.js:107:16)
   at Layer.handle [as handle_request] (C:\MediacenterJS\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\MediacenterJS\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\MediacenterJS\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\MediacenterJS\node_modules\express\lib\router\layer.js:95:5)
   at C:\MediacenterJS\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\MediacenterJS\node_modules\express\lib\router\index.js:330:12)
   at next (C:\MediacenterJS\node_modules\express\lib\router\index.js:271:10)
   at C:\MediacenterJS\node_modules\express\lib\application.js:232:9
   at C:\MediacenterJS\node_modules\express\lib\router\index.js:618:15
   at next (C:\MediacenterJS\node_modules\express\lib\router\index.js:256:14)
`

Running on windows 10 
"mediacenterjs" "version": "0.1.2"

**Comment by jansmolders86** [comment]
Which version of nodeJs are you using?

**Comment by mgara** [comment]
Still have the same issue .. I uninstalled my old node (v0.10) and installed the LTS (v4.2.2) however after installing v4.2.2 i had to install manyally the sqlite3 (npm install sqlite3) but Ive found my self with the same error on the browser. 
If you need more details I'm available,
else do you recommand i start from source ?

**Comment by jansmolders86** [comment]
yes please, I just pushed some fixes and reinstalled from scratch and it worked for me. just download the zip here on github and add the bin folder from the mediacenterjs-windows repo (or from your current mcjs install) then preform a npm install. I should work fine. I'll update the Windows setup asap
