### ISSUE TITLE
Sqlitle error

### ISSUE THREAD

**Issue by esfomeado** [jansmolders86/mediacenterjs#219]
Running on windows:

info: Starting server
module.js:340
    throw err;
    ^

Error: Cannot find module 'C:\MediacenterJS\node_modules\sqlite3\lib\binding\node-v47-win32-x64\node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\MediacenterJS\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\MediacenterJS\lib\utils\database-schema.js:2:14)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)

**Comment by tracker1** [comment]
Did you experience errors with `npm install`?

**Comment by jansmolders86** [comment]
Also, did you download the github master or the exe from the site? I just reinstalled the exe from the site with no issue.

**Comment by esfomeado** [comment]
Using the exe from the site.

I have this folder node-v46-win32-ia32 instead of node-v47-win32-x64.

**Comment by jansmolders86** [comment]
How recently have you downloaded the exe? I pushed a new version 2 weeks ago. 
Also did you install node-gyp globally using  "npm install node-gyp -g"

**Comment by esfomeado** [comment]
I just downloaded today again to test it and same problem.
I haven't installed npm on my computer. I just download the .exe and executed and that error came up.
Is there any need for me to run any npm commands?

**Comment by jansmolders86** [comment]
argh! My PC simply doesn't show this error, very frustrating! Let me try on someone elses pc.

**Comment by jansmolders86** [comment]
So I tried on another pc. from the getgo,I had issues with the master version. Because the dependencies for node-gyp weren't installed on the machine. see dependencies here: https://github.com/nodejs/node-gyp. After installing them though, and reinstalling the node modules. Things worked just fine. Would you mind trying that too?

**Comment by TRex22** [comment]
I found a quick fix for this: In the package.json change the sqlite3 entry to "sqlite3": "3.0.5",  Thats seemed to fix the issue for me on the latest Windows release

**Comment by jansmolders86** [comment]
Woot! Awesome! made the code change! Thanks @TRex22
