### ISSUE TITLE
App crashes when start

### ISSUE THREAD

**Issue by guilhermetog** [jansmolders86/mediacenterjs#242]
I've just installed on Windows, through the setup.exe.
When I try to run it crashes and close. I tried to run "npm start" in the console and it return this log:

```
module.js:549
    throw err;
    ^

Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at evalmachine.<anonymous>:31:26
    at Object.<anonymous> (C:\MediacenterJS\node_modules\fs-extra\node_modules\graceful-fs\fs.js:11:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediacenterjs@0.1.3 start: `node server.js`
npm ERR! Exit status 1
```
I tried 'npm update' without success.
What can I do to run it?

**Comment by eviabs** [comment]
I got this error too when I used the windows installer.

To overcome this,  I cloned the repo (you can also just download it as a zip file and extract it), ran `npm install` and then ran `node server.js`.

Now it works.
