### ISSUE TITLE
TypeError: Device.find is not a function Error after web setup completed

### ISSUE THREAD

**Issue by psychdragon** [jansmolders86/mediacenterjs#249]
TypeError: Device.find is not a function
    at Object.exports.isDeviceAllowed (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/lib/utils/device-utils.js:48:12)
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/index.js:119:20
    at Layer.handle [as handle_request] (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/application.js:233:9
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:635:15
    at next (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:260:14)
    at expressInit (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:275:10)
    at query (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:174:3)
    at Function.handle (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/application.js:174:10)
    at mounted_app (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/application.js:230:10)
    at Layer.handle [as handle_request] (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/application.js:233:9
    at /home/pi/ffmpeg_sources/ffmpeg/mediacenterjs/node_modules/express/lib/router/index.js:635:15

**Comment by smigou31** [comment]
do you resolved this ?
